spring:
  thymeleaf:
    mode: HTML5
    encoding: UTF-8
    cache: false # 开发时关闭缓存,不然没法看到实时页面
    prefix:
      classpath: /templates  #访问templates下的html文件需要配置模板，映射
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/user_db?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: root
server:
  port: 8080
  servlet:
    context-path: /spring-security

mybatis:
  mapper-locations: classpath:mapper/*.xml